format = '''
{type}{scope}: {emoji}{subject}
{body}
{footer}'''

[[types]]
description = 'A bug fix'
value = 'fix'
emoji = 'ğŸ›'

[[types]]
description = 'A new feature'
value = 'feat'
emoji = 'âœ¨'

[[types]]
description = 'Changes that introduces a breaking API change'
value = 'BREAKING CHANGE'
emoji = 'ğŸ’¥'

[[types]]
description = 'build system or external dependencies'
value = 'chore'
emoji = 'ğŸ› ï¸'

[[types]]
description = 'CI related changes'
value = 'ci'
emoji = 'ğŸ’«'

[[types]]
description = 'Documentation only changes'
value = 'docs'
emoji = 'âœï¸'

[[types]]
description = 'Changes that do not affect the meaning of the code'
value = 'style'
emoji = 'ğŸ’„'

[[types]]
description = 'A code change that neither fixes a bug nor adds a feature'
value = 'refactor'
emoji = 'ğŸ§¹'

[[types]]
description = ' A code change that improves performance'
value = 'perf'
emoji = 'ğŸš„'

[[types]]
description = 'Adding or correcting tests'
value = 'test'
emoji = 'ğŸ§ª'
